language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-express-static' ]; then cd .. && eval "mv $currentfolder generator-express-static" && cd generator-express-static; fi

